# Each variant is a separate production shaderpack. Only the fragment shader
# changes except for wrong-geometry, which deliberately corrupts the vertex
# feature boundary. Includes and resolve stay current in every variant.
file(READ "${SOURCE_DIR}/test/graphics/gpu/post343.glsl" post343)
set(lighting_line "    vec3 lighting = min(vec3(1.0), ambient + max(vec3(0.0), diffuse));")
string(FIND "${post343}" "${lighting_line}" lighting_pos)
if(lighting_pos LESS 0)
    message(FATAL_ERROR "Frozen post343 mutation anchor missing")
endif()
foreach(variant current pre343 post343 dedicated-only lighting-only global-fullbright wrong-geometry)
    set(variant_dir "${OUTPUT_DIR}/${variant}")
    file(MAKE_DIRECTORY "${variant_dir}/glsl")
    file(COPY "${SOURCE_DIR}/glsl/" DESTINATION "${variant_dir}/glsl")
    if(variant STREQUAL "pre343" OR variant STREQUAL "post343" OR variant STREQUAL "dedicated-only")
        configure_file("${SOURCE_DIR}/test/graphics/gpu/${variant}.glsl"
            "${variant_dir}/glsl/f_oit_model.glsl" COPYONLY)
    elseif(variant STREQUAL "lighting-only")
        string(REPLACE "${lighting_line}"
            "${lighting_line}\n    if (isFeatureEnabled(FEATURE_PREMULALPHA)) { lighting = vec3(1.0); }"
            mutated "${post343}")
        file(WRITE "${variant_dir}/glsl/f_oit_model.glsl" "${mutated}")
    elseif(variant STREQUAL "global-fullbright")
        string(REPLACE "${lighting_line}" "    vec3 lighting = vec3(1.0);"
            mutated "${post343}")
        file(WRITE "${variant_dir}/glsl/f_oit_model.glsl" "${mutated}")
    elseif(variant STREQUAL "wrong-geometry")
        file(READ "${SOURCE_DIR}/glsl/v_model.glsl" vertex)
        set(anchor "else if (isFeatureEnabled(FEATURE_SABER))")
        string(FIND "${vertex}" "${anchor}" vertex_pos)
        if(vertex_pos LESS 0)
            message(FATAL_ERROR "Saber geometry mutation anchor missing")
        endif()
        string(REPLACE "${anchor}"
            "else if (isFeatureEnabled(FEATURE_SABER) || isFeatureEnabled(FEATURE_PREMULALPHA))"
            vertex "${vertex}")
        file(WRITE "${variant_dir}/glsl/v_model.glsl" "${vertex}")
    endif()
    execute_process(COMMAND "${SHADERPACK}" "${variant_dir}/glsl" "${variant_dir}"
        RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "shaderpack failed for ${variant}: ${result}")
    endif()
endforeach()
file(WRITE "${OUTPUT_DIR}/prepared.stamp" "Generated by production shaderpack\n")
