from __future__ import annotations

import argparse
import html
import http.server
import json
import mimetypes
import os
import pathlib
import signal
import socket
import socketserver
import subprocess
import sys
import time
import urllib.parse

# IDE / odd launchers sometimes omit ``tools/web`` on sys.path; bundle resolution must still run.
_tools_web = pathlib.Path(__file__).resolve().parent
if str(_tools_web) not in sys.path:
    sys.path.insert(0, str(_tools_web))

from web_bundle_paths import find_reone_web_output_stamp, resolve_web_build_directory

_COMMON_DEV_PORTS = (4204, 4205, 4206, 4207, 4208, 11152)

# Served when ``--game-root`` is omitted so the browser does not log a failed network
# request for ``/game-manifest.json``. File picker / embedded preload modes ignore empty manifests.
_GAME_MANIFEST_STUB_BYTES = json.dumps(
    {"files": [], "directories": [], "reoneHttpMirror": False},
    separators=(",", ":"),
).encode("utf-8")

_MODULE_MIRROR_JSON = _tools_web / "module_mirror.json"


def _parse_bytes_range(range_header: str | None, file_size: int) -> tuple[int, int] | None:
    """Return inclusive (start, end) for a single Range spec, or None for full body."""
    if not range_header or not range_header.strip().lower().startswith("bytes="):
        return None
    spec = range_header.split("=", 1)[1].strip()
    if "," in spec:
        spec = spec.split(",", 1)[0].strip()
    spec = spec.strip()
    try:
        if spec.startswith("-"):
            suffix_len = int(spec[1:])
            if suffix_len <= 0:
                return None
            start = max(0, file_size - suffix_len)
            end = file_size - 1
            return start, end
        if "-" in spec:
            start_s, end_s = spec.split("-", 1)
            start = int(start_s) if start_s.strip() else 0
            end = int(end_s) if end_s.strip() else file_size - 1
        else:
            return None
    except ValueError:
        return None
    end = min(end, file_size - 1)
    if start < 0 or start >= file_size or start > end:
        return None
    return start, end


def _bundle_directory_index_bytes(root: pathlib.Path) -> bytes:
    """HTML listing of ``root`` via pathlib — avoids stdlib dir-index quirks / misleading listings."""
    root = root.resolve()
    rows: list[str] = []
    try:
        entries = sorted(root.iterdir(), key=lambda p: p.name.lower())
    except OSError as e:
        msg = html.escape(str(root))
        err = html.escape(str(e))
        return f'<!DOCTYPE html><html><body><pre>cannot list {msg}: {err}</pre></body></html>'.encode("utf-8")
    for p in entries:
        name = p.name
        if p.is_dir():
            rows.append(f"<li>{html.escape(name)}/</li>")
            continue
        try:
            sz = p.stat().st_size
        except OSError:
            sz = -1
        qn = urllib.parse.quote(name)
        sz_s = f"{sz}" if sz >= 0 else "?"
        rows.append(f'<li><a href="/{qn}">{html.escape(name)}</a> — {sz_s} bytes</li>')
    root_esc = html.escape(str(root))
    page = (
        "<!DOCTYPE html>\n"
        '<html lang="en"><head><meta charset="utf-8"><title>reone wasm bundle</title></head><body>\n'
        f"<h1>WASM bundle directory</h1>\n<p><code>{root_esc}</code></p>\n<ul>\n"
        + "".join(rows)
        + "</ul>\n<p><strong><a href=\"/engine.html\">Open engine.html</a></strong></p>\n"
        "<p><small>Generated by tools/web/serve.py (pathlib scan). "
        "Check response headers <code>X-Reone-Web-Root</code> / <code>X-Reone-Serve-Pid</code> in DevTools.</small></p>\n"
        "</body></html>\n"
    )
    return page.encode("utf-8")


class WebBuildRequestHandler(http.server.SimpleHTTPRequestHandler):
    """Serve WASM build from ``directory`` and optional lazy game files from ``game_root``."""

    def __init__(
        self,
        *args,
        game_root: pathlib.Path | None = None,
        serve_pid: int | None = None,
        **kwargs,
    ):
        self._lazy_game_root = game_root.resolve() if game_root else None
        self._reone_serve_pid = serve_pid
        super().__init__(*args, **kwargs)

    def end_headers(self):
        request_path = self.path.split("?", 1)[0]
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
        self.send_header("Cross-Origin-Resource-Policy", "same-origin")
        # Prove in DevTools → Network that this is ``tools/web/serve.py`` and which folder is listed.
        if os.environ.get("REONE_SERVE_NO_META_HEADERS", "").strip().lower() not in ("1", "true", "yes"):
            if self._reone_serve_pid is not None:
                self.send_header("X-Reone-Serve-Pid", str(self._reone_serve_pid))
            try:
                self.send_header(
                    "X-Reone-Web-Root",
                    pathlib.Path(self.directory).resolve().as_posix(),
                )
            except OSError:
                pass
        if request_path.endswith((".data", ".wasm", ".js")):
            self.send_header("Cache-Control", "public, max-age=0, must-revalidate")
        else:
            self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def copyfile(self, source, outputfile):
        chunk_size = 256 * 1024
        buffer = bytearray(chunk_size)
        view = memoryview(buffer)
        range_tuple = getattr(self, "range", None)
        remaining = None
        if isinstance(range_tuple, tuple) and len(range_tuple) == 2:
            start, end = range_tuple
            if isinstance(start, int) and isinstance(end, int) and end >= start:
                remaining = end - start + 1
        try:
            while True:
                if remaining is not None:
                    if remaining <= 0:
                        break
                    read_bytes = source.readinto(view[: min(chunk_size, remaining)])
                else:
                    read_bytes = source.readinto(buffer)
                if not read_bytes:
                    break
                outputfile.write(view[:read_bytes])
                if remaining is not None:
                    remaining -= read_bytes
        except (BrokenPipeError, ConnectionResetError, socket.timeout):
            return

    def _serve_bundle_directory_index(self, *, head_only: bool) -> None:
        root = pathlib.Path(self.directory).resolve()
        body = _bundle_directory_index_bytes(root)
        self.send_response(http.HTTPStatus.OK)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if not head_only:
            self.wfile.write(body)

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path_only = urllib.parse.unquote(parsed.path)
        if path_only in ("/", ""):
            self._serve_bundle_directory_index(head_only=False)
            return
        if path_only == "/game-manifest.json":
            self._serve_game_manifest()
            return
        if path_only == "/module_mirror.json":
            self._serve_module_mirror_json(head_only=False)
            return
        if path_only.startswith("/game-files/"):
            rel = path_only[len("/game-files/") :]
            self._serve_lazy_game_file(rel)
            return
        super().do_GET()

    def do_HEAD(self):
        parsed = urllib.parse.urlparse(self.path)
        path_only = urllib.parse.unquote(parsed.path)
        if path_only in ("/", ""):
            self._serve_bundle_directory_index(head_only=True)
            return
        if path_only == "/game-manifest.json":
            self._serve_game_manifest(head_only=True)
            return
        if path_only == "/module_mirror.json":
            self._serve_module_mirror_json(head_only=True)
            return
        if path_only.startswith("/game-files/"):
            rel = path_only[len("/game-files/") :]
            self._serve_lazy_game_file(rel, head_only=True)
            return
        super().do_HEAD()

    def _resolve_under_game_root(self, relative_url_path: str) -> pathlib.Path | None:
        if not self._lazy_game_root:
            return None
        rel = urllib.parse.unquote(relative_url_path).replace("\\", "/").lstrip("/")
        if not rel or rel.endswith("/"):
            return None
        parts = pathlib.PurePosixPath(rel).parts
        if ".." in parts:
            return None
        full = (self._lazy_game_root / pathlib.Path(*parts)).resolve()
        try:
            full.relative_to(self._lazy_game_root)
        except ValueError:
            return None
        return full

    def _serve_module_mirror_json(self, *, head_only: bool = False):
        if not _MODULE_MIRROR_JSON.is_file():
            self.send_error(404, "module_mirror.json missing under tools/web")
            return
        self._send_local_file(_MODULE_MIRROR_JSON, head_only=head_only)

    def _serve_game_manifest(self, *, head_only: bool = False):
        if not self._lazy_game_root:
            self.send_response(http.HTTPStatus.OK)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(_GAME_MANIFEST_STUB_BYTES)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            if not head_only:
                self.wfile.write(_GAME_MANIFEST_STUB_BYTES)
            return
        manifest_path = self._lazy_game_root / "game-manifest.json"
        if not manifest_path.is_file():
            self.send_error(
                404,
                "game-manifest.json not found under game root — run tools/web/gen_game_manifest.py",
            )
            return
        self._send_local_file(manifest_path, head_only=head_only)

    def _serve_lazy_game_file(self, relative_url_path: str, *, head_only: bool = False):
        full_path = self._resolve_under_game_root(relative_url_path)
        if full_path is None:
            self.send_error(403 if self._lazy_game_root else 503)
            return
        if not full_path.is_file():
            self.send_error(404)
            return
        self._send_local_file(full_path, head_only=head_only)

    def _send_local_file(self, full_path: pathlib.Path, *, head_only: bool = False):
        file_size = full_path.stat().st_size
        ctype = mimetypes.guess_type(str(full_path))[0] or "application/octet-stream"
        range_pair = _parse_bytes_range(self.headers.get("Range"), file_size)

        try:
            f = open(full_path, "rb")
        except OSError:
            self.send_error(403)
            return

        with f:
            if range_pair is None:
                self.send_response(http.HTTPStatus.OK)
                self.send_header("Content-Type", ctype)
                self.send_header("Content-Length", str(file_size))
                self.send_header("Accept-Ranges", "bytes")
                self.end_headers()
                if not head_only:
                    self.copyfile(f, self.wfile)
                return

            start, end = range_pair
            chunk_len = end - start + 1
            self.send_response(http.HTTPStatus.PARTIAL_CONTENT)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(chunk_len))
            self.send_header("Content-Range", f"bytes {start}-{end}/{file_size}")
            self.send_header("Accept-Ranges", "bytes")
            self.end_headers()
            if head_only:
                return
            f.seek(start)
            remaining = chunk_len
            buf_size = 256 * 1024
            while remaining > 0:
                n = min(buf_size, remaining)
                data = f.read(n)
                if not data:
                    break
                self.wfile.write(data)
                remaining -= len(data)


def check_web_bundle(directory: pathlib.Path) -> list[str]:
    """Return fatal issue strings for ``directory``; empty means OK to serve."""
    names = ("engine.html", "engine.js", "engine.wasm", "engine.data")
    missing = [n for n in names if not (directory / n).is_file()]
    if missing:
        return [
            "reone serve: incomplete wasm bundle under "
            f"{directory} (missing: {', '.join(missing)}). "
            "Rebuild the ``engine`` target (Emscripten). "
            "On Windows, outputs may be under %TEMP%/reone-emscripten-* (see reone-web-output-dir.txt next to your "
            "build dir); a successful link should also copy artifacts into build-…/bin when outside-repo staging is enabled."
        ]

    try:
        wasm_sz = (directory / "engine.wasm").stat().st_size
        html_sz = (directory / "engine.html").stat().st_size
        js_sz = (directory / "engine.js").stat().st_size
    except OSError as e:
        return [f"reone serve: cannot stat wasm bundle under {directory}: {e}"]
    errs: list[str] = []
    if wasm_sz < 32768:
        errs.append(
            f"reone serve: {directory / 'engine.wasm'} is only {wasm_sz} bytes — "
            "link likely failed or the file is locked. Close browsers/serve.py, rebuild ``engine``, retry."
        )
    if html_sz < 200:
        errs.append(f"reone serve: engine.html looks truncated ({html_sz} bytes) under {directory}.")
    if js_sz < 500:
        errs.append(f"reone serve: engine.js looks truncated ({js_sz} bytes) under {directory}.")
    return errs


def ensure_web_bundle_present(directory: pathlib.Path) -> None:
    """Fail fast when the tree only has a stale ``engine.data`` or a partial link."""
    errs = check_web_bundle(directory)
    if errs:
        sys.exit("\n".join(errs))


def _windows_netstat_listening_lines_for_port(port: int) -> list[str]:
    try:
        r = subprocess.run(
            ["netstat", "-ano", "-p", "tcp"],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return []
    needle = f":{port}"
    out: list[str] = []
    for line in r.stdout.splitlines():
        if "LISTENING" not in line:
            continue
        parts = line.split()
        if len(parts) < 5:
            continue
        if parts[1].endswith(needle):
            out.append(line.strip())
    return out


def _describe_bundle_files(base: pathlib.Path) -> None:
    names = ("engine.html", "engine.js", "engine.wasm", "engine.data")
    print(f"  under {base}:", flush=True)
    for n in names:
        p = base / n
        if not p.is_file():
            print(f"    {n}: (missing)", flush=True)
            continue
        try:
            print(f"    {n}: {p.stat().st_size} bytes", flush=True)
        except OSError as e:
            print(f"    {n}: (stat error {e})", flush=True)


def run_diag(args: argparse.Namespace) -> int:
    """Print paths, stamp, bundle layout, listeners — exit before HTTP (for debugging “only engine.data”)."""
    print("reone serve --diag", flush=True)
    print("this script:", pathlib.Path(__file__).resolve(), flush=True)
    print("cwd:", pathlib.Path.cwd().resolve(), flush=True)
    raw = pathlib.Path(args.directory).expanduser().resolve()
    stamp = find_reone_web_output_stamp(raw)
    resolved = resolve_web_build_directory(raw)
    print("--directory:", raw, flush=True)
    print("stamp:", stamp if stamp else "(none found walking up from --directory)", flush=True)
    if stamp is not None and stamp.is_file():
        try:
            print("stamp body:", repr(stamp.read_text(encoding="utf-8").strip()), flush=True)
        except OSError as e:
            print(f"stamp read error: {e}", flush=True)
    print("resolved HTTP root:", resolved, flush=True)
    if raw != resolved:
        print(
            "NOTE: Explorer may show only stale files under --directory while this serve.py uses "
            "resolved HTTP root above.",
            flush=True,
        )
    print("--- files under --directory ---", flush=True)
    _describe_bundle_files(raw)
    print("--- files under resolved HTTP root ---", flush=True)
    _describe_bundle_files(resolved)

    ports = sorted(set(_COMMON_DEV_PORTS + (args.port,)))
    print("--- TCP LISTENING (selected ports) ---", flush=True)
    if sys.platform == "win32":
        found_any = False
        for port in ports:
            lines = _windows_netstat_listening_lines_for_port(port)
            if lines:
                found_any = True
                print(f" :{port}", flush=True)
                for ln in lines:
                    print(f"   {ln}", flush=True)
        if not found_any:
            print(" (no listeners on scanned ports)", flush=True)
    else:
        found_any = False
        for port in ports:
            try:
                r = subprocess.run(
                    ["lsof", "-nP", f"-iTCP:{port}", "-sTCP:LISTEN"],
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
            except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
                continue
            if r.stdout.strip():
                found_any = True
                print(f" :{port}", flush=True)
                print(r.stdout.rstrip(), flush=True)
        if not found_any:
            print(" (no listeners on scanned ports)", flush=True)

    errs = check_web_bundle(resolved)
    if errs:
        print("--- bundle check ---", flush=True)
        for e in errs:
            print(e, flush=True)
        print(
            "\nIf the browser shows only engine.data but this script looks OK, "
            "another process may still be bound to this port — compare netstat PIDs above.",
            flush=True,
        )
        return 1
    print("--- bundle check: OK ---", flush=True)
    return 0


def _log_bundle_sizes(directory: pathlib.Path) -> None:
    names = ("engine.html", "engine.js", "engine.wasm", "engine.data")
    parts: list[str] = []
    for n in names:
        p = directory / n
        try:
            parts.append(f"{n}={p.stat().st_size}")
        except OSError:
            parts.append(f"{n}=?")
    print("reone serve: wasm bundle — " + ", ".join(parts), flush=True)


def _nuke_tcp_listener_on_port(port: int) -> None:
    """Kill LISTENING processes on ``port`` (best-effort; matches smoke_engine_menu nuke semantics)."""
    if sys.platform == "win32":
        seen: set[str] = set()
        for line in _windows_netstat_listening_lines_for_port(port):
            parts = line.split()
            if len(parts) < 5:
                continue
            pid_s = parts[-1]
            if not pid_s.isdigit() or pid_s in seen:
                continue
            seen.add(pid_s)
            print(f"reone serve: taskkill LISTENING PID {pid_s} :{port}", flush=True)
            subprocess.run(
                ["taskkill", "/F", "/T", "/PID", pid_s],
                capture_output=True,
                text=True,
                timeout=60,
            )
        return

    try:
        r = subprocess.run(
            ["lsof", "-t", f"-iTCP:{port}", "-sTCP:LISTEN"],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return
    for pid_s in r.stdout.strip().split():
        if not pid_s.isdigit():
            continue
        try:
            pid = int(pid_s)
            print(f"reone serve: SIGTERM listener PID {pid} :{port}", flush=True)
            os.kill(pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            pass


class ReusableThreadingTCPServer(socketserver.ThreadingTCPServer):
    """On Windows, ``SO_REUSEADDR`` allows multiple unrelated listeners on the same port (broken HTTP)."""

    allow_reuse_address = sys.platform != "win32"
    daemon_threads = True


class ReusableDualStackThreadingTCPServer(socketserver.ThreadingTCPServer):
    """Listen on IPv6 ``::`` with ``IPV6_V6ONLY=0`` so ``localhost`` (often ::1) and IPv4 clients both work."""

    allow_reuse_address = sys.platform != "win32"
    daemon_threads = True
    address_family = socket.AF_INET6

    def server_bind(self) -> None:
        self.socket.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
        super().server_bind()


def _handler_factory(
    web_directory: pathlib.Path,
    game_root: pathlib.Path | None,
    serve_pid: int,
):
    wd = web_directory.resolve()
    gr = game_root.resolve() if game_root else None

    def _factory(request, client_address, server):
        return WebBuildRequestHandler(
            request,
            client_address,
            server,
            directory=str(wd),
            game_root=gr,
            serve_pid=serve_pid,
        )

    return _factory


def main():
    parser = argparse.ArgumentParser(description="Serve the reone WebAssembly build")
    parser.add_argument("--directory", default="build-web/bin", help="directory containing engine.html")
    parser.add_argument(
        "--game-root",
        default=None,
        help="KotOR install directory (serves /game-manifest.json and /game-files/... for lazy loading)",
    )
    parser.add_argument("--port", type=int, default=4205, help="localhost port")
    parser.add_argument(
        "--nuke-port",
        action="store_true",
        help="Kill LISTENING processes on --port before bind (always implied on Windows unless REONE_SERVE_NO_NUKE=1)",
    )
    parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Bind address (default 127.0.0.1, matches smoke tests). Use :: for dual-stack IPv6+IPv4.",
    )
    parser.add_argument(
        "--diag",
        action="store_true",
        help="Print wasm paths, stamp, listeners on dev ports, bundle check; exit (no HTTP server)",
    )
    parser.add_argument(
        "--nuke-common-ports",
        action="store_true",
        help=(
            "Kill listeners on 4204–4208 and 11152 after primary cleanup "
            "(also default on Windows with primary nuke; set REONE_SERVE_NO_COMMON_NUKE=1 to skip)"
        ),
    )
    args = parser.parse_args()

    if args.diag:
        raise SystemExit(run_diag(args))

    mimetypes.add_type("application/wasm", ".wasm")
    mimetypes.add_type("application/json", ".json")
    raw_web_dir = pathlib.Path(args.directory).expanduser().resolve()
    directory = resolve_web_build_directory(raw_web_dir)
    if directory != raw_web_dir:
        print(
            f"reone serve: resolved --directory {raw_web_dir} -> {directory} "
            "(CMake/reone-web-output-dir.txt redirect)",
            flush=True,
        )
    game_root = pathlib.Path(args.game_root).resolve() if args.game_root else None
    if game_root and not (directory / "engine.html").is_file():
        print(
            f"reone serve: game-mirror-only mode — serving /game-* from {game_root} "
            f"(no wasm bundle under {directory})",
            flush=True,
        )
    else:
        ensure_web_bundle_present(directory)
        _log_bundle_sizes(directory)
    handler_factory = _handler_factory(directory, game_root, os.getpid())

    host = (args.host or "127.0.0.1").strip()
    _env_no_nuke = os.environ.get("REONE_SERVE_NO_NUKE", "").strip().lower() in ("1", "true", "yes")
    _win_nuke_default = sys.platform == "win32" and not _env_no_nuke
    _win_nuke_common_default = (
        sys.platform == "win32"
        and not _env_no_nuke
        and os.environ.get("REONE_SERVE_NO_COMMON_NUKE", "").strip().lower() not in ("1", "true", "yes")
    )
    if args.nuke_port or _win_nuke_default:
        why = "Windows default (set REONE_SERVE_NO_NUKE=1 to skip)" if _win_nuke_default and not args.nuke_port else "--nuke-port"
        print(f"reone serve: clearing TCP listeners on :{args.port} ({why}) …", flush=True)
        _nuke_tcp_listener_on_port(args.port)
        time.sleep(0.35)

    if args.nuke_common_ports or _win_nuke_common_default:
        extra = [p for p in _COMMON_DEV_PORTS if p != args.port]
        if extra:
            why = (
                "Windows default (REONE_SERVE_NO_COMMON_NUKE=1 to skip)"
                if _win_nuke_common_default and not args.nuke_common_ports
                else "--nuke-common-ports"
            )
            print(f"reone serve: clearing other dev ports {extra} ({why}) …", flush=True)
            for p in extra:
                _nuke_tcp_listener_on_port(p)
            time.sleep(0.3)

    listen_dual_stack = False
    if host in ("::", "[::]", "all-ipv6"):
        listen_dual_stack = True
        try:
            server_cm = ReusableDualStackThreadingTCPServer(("::", args.port), handler_factory)
        except OSError as e:
            print(f"Dual-stack bind on :: failed ({e}); falling back to 127.0.0.1.", flush=True)
            listen_dual_stack = False
            server_cm = ReusableThreadingTCPServer(("127.0.0.1", args.port), handler_factory)
    else:
        bind_addr = (host, args.port)
        try:
            server_cm = ReusableThreadingTCPServer(bind_addr, handler_factory)
        except OSError as e:
            win_busy = sys.platform == "win32" and getattr(e, "winerror", None) == 10048
            if win_busy:
                print(
                    f"Port {args.port} is already in use; attempting one-shot listener cleanup "
                    "(stale ``serve.py`` / Windows SO_REUSEADDR). Original error: {e}",
                    flush=True,
                )
                _nuke_tcp_listener_on_port(args.port)
                time.sleep(0.35)
                try:
                    server_cm = ReusableThreadingTCPServer(bind_addr, handler_factory)
                except OSError as e2:
                    print(
                        f"Still cannot bind :{args.port} after cleanup ({e2}). "
                        "Choose another ``--port`` or stop the other process; "
                        "set REONE_SERVE_NO_NUKE=1 only if you intentionally share the port.",
                        flush=True,
                    )
                    raise
            else:
                raise

    with server_cm as server:
        print(
            f"reone serve: pid={os.getpid()} — netstat LISTENING row for :{args.port} must match this PID "
            "or you are hitting a different server.",
            flush=True,
        )
        extra = f" game-root={game_root}" if game_root else ""
        if host == "0.0.0.0":
            print(f"Serving {directory} on 0.0.0.0:{args.port} (try http://127.0.0.1:{args.port}){extra}", flush=True)
        elif listen_dual_stack:
            print(f"Serving {directory} dual-stack :: — http://127.0.0.1:{args.port}{extra}", flush=True)
            print(f"Also http://[::1]:{args.port}{extra}", flush=True)
        else:
            print(f"Serving {directory} at http://{host}:{args.port}{extra}", flush=True)
        if game_root:
            print(
                "HTTP game mirror: ON (lazy Range reads via /game-manifest.json + /game-files/...). "
                "Do not use this for retail folder-picker testing.",
                flush=True,
            )
        else:
            print(
                "HTTP game mirror: OFF. Folder picker / File System Access: open "
                f"http://127.0.0.1:{args.port}/engine.html?reoneFs=picker",
                flush=True,
            )
        server.serve_forever()


if __name__ == "__main__":
    main()
