name: Build and run tests on Linux
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "ubuntu:25.10"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-linux
