name: Build and run tests on Linux
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "ubuntu:25.10"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |-
          apt-get update
          apt install --no-install-recommends -y \
            cmake build-essential g++ \
            libboost-all-dev libsdl2-dev libsdl3-dev libglew-dev libopenal-dev libmad0-dev libwxgtk3.2-dev libgmock-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev

      - name: Create Build Environment
        working-directory: ${{github.workspace}}
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .

      - name: Run Unit Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -VV
