name: Build and run tests on Windows
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
env:
  VCPKG_ROOT: C:/vcpkg

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-windows
