name: Build a release on Windows
on:
  push:
    tags: ["*"]
  workflow_dispatch:
env:
  VCPKG_ROOT: C:/vcpkg
  RELEASE: reone-${{ github.ref_name }}
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-windows

      - name: Zip
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |-
          mkdir $RELEASE
          mv bin $RELEASE/
          7z a -r $RELEASE.zip $RELEASE

      - name: Tag a release
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |-
          gh release create $TAG $RELEASE.zip \
            --title "Reone $TAG" \
            --notes "Commit: ${{github.sha}}" \
            --draft --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
